### ISSUE TITLE
Unable to run "Client()".

### ISSUE THREAD

**Issue by ghost** [reiyw/mirai-translate#32]
This will result in an error like this.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 4, in __init__
  File "C:\Users\ikki1\AppData\Local\Programs\Python\Python38\lib\site-packages\mirai_translate\lib.py", line 24, in __post_init__
    self._refresh_tran()
  File "C:\Users\ikki1\AppData\Local\Programs\Python\Python38\lib\site-packages\mirai_translate\lib.py", line 37, in _refresh_tran
    self._tran = soup.find(id="tranInput")["value"]
TypeError: 'NoneType' object is not subscriptable

**Comment by reiyw** [comment]
Thank you for reporting the issue! It is now should be fixed. Can you try again after upgrading?
```
pip install -U mirai-translate
```

**Comment by ghost** [comment]
It worked fine. Thank you for the revision.
